### ISSUE TITLE
Errors when used with jest --watchAll

### ISSUE THREAD

**Issue by jingchan** [stackgl/headless-gl#103]
When running with `jest --watchAll`, the following code will work on the initial test, but subsequent changes, which cause the tester to re-run the tests, will fail on context creation.

```
import GL from 'gl';
let gl = GL(100, 100);
```

On first run, will pass.

On second run, will cause this error:
```
    TypeError: framebufferTexture2D(GLenum, GLenum, GLenum, WebGLTexture, GLint)
      
      at WebGLRenderingContext.framebufferTexture2D (node_modules/gl/webgl.js:2300:11)
      at resizeDrawingBuffer (node_modules/gl/webgl.js:4096:27)
      at Object.allocateDrawingBuffer (node_modules/gl/webgl.js:4079:3)
      at createContext (node_modules/gl/node_index.js:107:9)
      at Object.<anonymous> (shader.spec.js:13:55)

```

On third and subsequent runs, will cause this error:
```
    TypeError: bindFramebuffer(GLenum, WebGLFramebuffer)
      
      at WebGLRenderingContext.bindFramebuffer (node_modules/gl/webgl.js:1054:11)
      at WebGLRenderingContext.bindFramebuffer (node_modules/gl/webgl.js:1068:22)
      at resizeDrawingBuffer (node_modules/gl/webgl.js:4092:20)
      at Object.allocateDrawingBuffer (node_modules/gl/webgl.js:4079:3)
      at createContext (node_modules/gl/node_index.js:107:9)
      at Object.<anonymous> (shader.spec.js:13:55)
```

I don't mind looking into this issue, but I'd need a bit of direction on where to look.

**Comment by pconerly** [comment]
@jingchan We're having the same issue. Did you find a solution? Why did you close this issue?
