### ISSUE TITLE
Error creating WebGLContext on Raspberry Pi

### ISSUE THREAD

**Issue by flimshaw** [stackgl/headless-gl#118]
After installing the pre-reqs, everything built perfectly on the raspberry pi 3, but I get errors trying to create a webgl context. Is operation on embedded platforms like the raspi possible?

I'm getting the following error:

```
pi@betty:~ $ noisemaker -o test.png
/usr/lib/node_modules/noisemaker/node_modules/headless-gl/index.js:39
  var gl = new webgl.WebGLRenderingContext(
           ^

Error: Error creating WebGLContext
    at Error (native)
    at createContext (/usr/lib/node_modules/noisemaker/node_modules/headless-gl/index.js:39:12)
    at Object.<anonymous> (/usr/lib/node_modules/noisemaker/index.js:37:34)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3
```

Trying to install and use this npm library: https://www.npmjs.com/package/noisemaker

Thanks a lot, wonderful library!

**Comment by samelie** [comment]
increasing GPU memory to `128` solved this. 
Running this before node in the same shell also let me use the library as an npm module:
```
sudo apt-get install xvfb
Xvfb :1 -screen 0 1024x768x24 </dev/null &
export DISPLAY=":1"
```
