### ISSUE TITLE
multiple-render-targets tests fails on windows

### ISSUE THREAD

**Issue by dhritzkiv** [stackgl/headless-gl#147]
[From this build](https://ci.appveyor.com/project/dhritzkiv/headless-gl/builds/23060235#L1535)

```
1535# multiple-render-targets
1537    ---
1538      operator: equal
1539      expected: 16
1540      actual:   0
1541      at: Test.<anonymous> (C:\projects\headless-gl\test\multiple-render-targets.js:23:5)
1542      stack: |-
1543        Error: Only 0 are not 0, expected 16
1544            at Test.assert [as _assert] (C:\projects\headless-gl\node_modules\tape\lib\test.js:226:54)
1545            at Test.bound [as _assert] (C:\projects\headless-gl\node_modules\tape\lib\test.js:77:32)
1546            at Test.equal (C:\projects\headless-gl\node_modules\tape\lib\test.js:386:10)
1547            at Test.bound [as equals] (C:\projects\headless-gl\node_modules\tape\lib\test.js:77:32)
1548            at Test.<anonymous> (C:\projects\headless-gl\test\multiple-render-targets.js:23:5)
1549            at Test.bound [as _cb] (C:\projects\headless-gl\node_modules\tape\lib\test.js:77:32)
1550            at Test.run (C:\projects\headless-gl\node_modules\tape\lib\test.js:96:10)
1551            at Test.bound [as run] (C:\projects\headless-gl\node_modules\tape\lib\test.js:77:32)
1552            at Immediate.next [as _onImmediate] (C:\projects\headless-gl\node_modules\tape\lib\results.js:75:19)
1553            at runCallback (timers.js:705:18)
1554    ...
```

**Comment by robertleeplummerjr** [comment]
Starting investigation.

**Comment by robertleeplummerjr** [comment]
@dhritzkiv while you are looking into the build system, any chance this looks remotely familiar for solving?  I starting looking into it sometime back, but got distracted.

**Comment by dhritzkiv** [comment]
I took a cursory look at it last night, but didn't see any obvious issues, especially since we're using `readPixels` like we do in other tests. Have no idea what it could be.

I don't know how to test this without actually running on Windows.

**Comment by robertleeplummerjr** [comment]
Found it!  Will have a pr before day's end.
