### ISSUE TITLE
Issues with resolution on using xvfb-run -s "-ac -screen 0 1280x1024x24" 

### ISSUE THREAD

**Issue by javeedrahman** [stackgl/headless-gl#175]
Hi,

I am trying to run the ffmpeg-concat command using --> "xvfb-run -s "-ac -screen 0 1280x1024x24" <node program>" and my video have 1920x1080 resolution.

When i change resolution and run the command "xvfb-run -s "-ac -screen 0 1920x1080x24" <node program>"  I am getting error.

Here is the command and output

```
xvfb-run -s "-ac -screen 0 2000x1100x24" ffmpeg-concat -t circleopen -d 750 -o app/media/2/output/1/final_outpup.mp4 app/media/2/output/1/6537_output.mp4 app/media/2/output/1/2105_output.mp4
{ cmd:
   'ffmpeg -i app/media/2/output/1/6537_output.mp4 -y -pix_fmt rgba -start_number 0 /tmp/efd2c7e32c45a9f81259fc6aa39ef0bd/scene-0-%012d.raw' }
{ cmd:
   'ffmpeg -i app/media/2/output/1/2105_output.mp4 -y -pix_fmt rgba -start_number 0 /tmp/efd2c7e32c45a9f81259fc6aa39ef0bd/scene-1-%012d.raw' }
ffmpeg-concat: 71909.316ms
concat error Error: ffmpeg exited with code 1: av_interleaved_write_frame(): Input/output error
frame=  242 fps=3.9 q=-0.0 Lsize=N/A time=00:00:08.07 bitrate=N/A    
video:1960200kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!

    at ChildProcess.<anonymous> (/opt/cpanel/ea-nodejs10/lib/node_modules/ffmpeg-concat/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
(node:471) UnhandledPromiseRejectionWarning: Error: ffmpeg exited with code 1: av_interleaved_write_frame(): Input/output error
frame=  242 fps=3.9 q=-0.0 Lsize=N/A time=00:00:08.07 bitrate=N/A    
video:1960200kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!

    at ChildProcess.<anonymous> (/opt/cpanel/ea-nodejs10/lib/node_modules/ffmpeg-concat/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
(node:471) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:471) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Thanks in Advance.

**Comment by robertleeplummerjr** [comment]
If this was something inside of or related to this library, it would likely be in a `gl` folder.  I don't see that from the stack trace, and while I would like to help with this issue I am unfamiliar with both `ffmpeg-concat` and `fluent-ffmpeg`.  I'd open your issue where those repository's issues are handled, and try and get some help that way.

**Comment by javeedrahman** [comment]
Thank you @robertleeplummerjr  
okay Please
