### ISSUE TITLE
no prebuilt binaries found

### ISSUE THREAD

**Issue by raghuv9** [stackgl/headless-gl#176]
Unable to install ffmpeg-concat on windows
--------------------------------------------------------------------------------------------------------
Hey,i tried to install ffmpeg-concat as mentioned in the docs,before i tried this using latest versions of node and python i faced the same error, after going through the closed issues as suggested by author in one of those closed issues,i have uninstalled the latest node version and installed node-8 and python 2.7 , still i'm getting the following errors.
![Screenshot (6)](https://user-images.githubusercontent.com/26516842/68026301-553ff800-fcd5-11e9-83c9-a68f665363c6.png).

here are the steps i have followed to install ffmpeg-concat
-------------------------------------------------------
npm install --global --production windows-build-tools
npm install --global node-gyp
setx PYTHON "path\python27\python.exe"
npm install -g ffmpeg-concat.

**Comment by dhritzkiv** [comment]
Just to clarify, are those errors or warnings? They seem like warnings.

Could you please paste the entire (or at least the most relevant) output as a text comment?

**Comment by raghuv9** [comment]
These are the errors i'm facing 
----------------------------------------------------------------------------------------------------------------
**npm install --save ffmpeg-concat

> gl@4.4.0 install C:\vue\vmaker\vmaker\node_modules\gl
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=13.0.1 runtime=node arch=ia32 libc= platform=win32)

C:\vue\vmaker\vmaker\node_modules\gl>if not defined npm_config_node_gyp (node "C:\Users\rv\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\rv\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Warning: Missing input files:
C:\vue\vmaker\vmaker\node_modules\gl\deps\windows\dll\ia32\libGLESv2.dll
C:\vue\vmaker\vmaker\node_modules\gl\deps\windows\dll\ia32\libEGL.dll
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Copying C:\vue\vmaker\vmaker\node_modules\gl/deps/windows/dll/ia32/libEGL.dll to C:\vue\vmaker\vmaker\node_modu
  les\gl\build\Release\libEGL.dll
  The system cannot find the path specified.
  Copying C:\vue\vmaker\vmaker\node_modules\gl/deps/windows/dll/ia32/libGLESv2.dll to C:\vue\vmaker\vmaker\node_m
  odules\gl\build\Release\libGLESv2.dll
  The system cannot find the path specified.
  bindings.cc
  webgl.cc
  procs.cc
  win_delay_load_hook.cc
LINK : fatal error LNK1104: cannot open file 'libEGL.lib' [C:\vue\vmaker\vmaker\node_modules\gl\build\webgl.vcxpr
oj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Raghu.vissapragada\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\rv\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\vue\vmaker\vmaker\node_modules\gl
gyp ERR! node -v v13.0.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gl@4.4.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gl@4.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rv\AppData\Roaming\npm-cache\_logs\2019-12-03T12_15_11_787Z-debug.log**

**Comment by dhritzkiv** [comment]
Thanks @raghuv9 

I noticed that your machine is 32bit (ia32). As such, I don't believe this library has dll files for 32 bit Windows: https://github.com/stackgl/headless-gl/tree/master/deps/windows 

I'm actually surprised to see that nodejs is able to run on 32bit platforms (all other platforms are 64bit only)!
I don't have a ton of development experience on Windows, so unfortunately, I can't be of much help. I don't know where the 64bit library files in this library originally came from.

The only thing I can think of is following instructions on building OpenGL, and copying the produced 32bit libEGL.dll and libGLESv2.dll files into the `deps/windows` directory. But I can't help you with that :(

**Comment by dhritzkiv** [comment]
A possibly quick trick that might work: You could open the Google Chrome install folder and look for libegl.dll, libglesv2.dll inside there, and then copy those files to the headless-gl deps folders.

**Comment by dhritzkiv** [comment]
Otherwise, you could try building Angle separately (more complicated), and copying the dll / lib files over: https://chromium.googlesource.com/angle/angle/+/HEAD/doc/DevSetup.md
