### ISSUE TITLE
Segfault when testing with jest

### ISSUE THREAD

**Issue by 1danielcoelho** [stackgl/headless-gl#188]
Not sure if I'm doing something wrong, but a simple repo with just these two files:

`package.json`:

    {
      "name": "testwebgl",
      "version": "1.0.0",
      "description": "",
      "main": "index.js",
      "scripts": {
        "test": "jest --no-cache"
      },
      "keywords": [],
      "author": "",
      "license": "ISC",
      "devDependencies": {
        "canvas": "^2.6.1",
        "gl": "^4.5.0",
        "jest": "^25.4.0"
      }
    }

`a.test.js`:

    describe('Test', () =>
    {
        test('initializes correctly', () =>
        {
            const context = require('gl')(800, 600);
            console.log(context);
        });
    });

Just completely segfaults when testing with `npm run test` with this error message:

```
Exception code=0xc0000005 flags=0x0 at 0x0000000000000000. Access violation - attempting to execute data at address 0x0000000000000000
npm ERR! code ELIFECYCLE
npm ERR! errno 3221225477
npm ERR! testwebgl@1.0.0 test: `jest --no-cache`
npm ERR! Exit status 3221225477
npm ERR!
npm ERR! Failed at the testwebgl@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I can confirm (by just not calling the function and logging the result of the require) that it can import `gl` correctly, and it seems to be a valid function. The segfault comes from something internal to `gl`.

The same also happens if I setup a `jest.config.js` that looks like this (i.e. this happens with both `jsdom` and `node` environments):

    module.exports = {
        testEnvironment: 'node'
    };

Except that the error message doesn't include the initial segfault part for the `node` environment.

Here is the output of running `npm run test --verbose` (for the `jsdom` environment):
```
npm verb lifecycle testwebgl@1.0.0~test: CWD: E:\Webdev\testwebgl
npm info lifecycle testwebgl@1.0.0~test: Failed to exec test script
npm verb stack Error: testwebgl@1.0.0 test: `jest --no-cache`
npm verb stack Exit status 3221225477
npm verb stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
npm verb stack     at EventEmitter.emit (events.js:311:20)
npm verb stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:311:20)
npm verb stack     at maybeClose (internal/child_process.js:1021:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
npm verb pkgid testwebgl@1.0.0
npm verb cwd E:\Webdev\testwebgl
npm verb Windows_NT 10.0.18363
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test" "--verbose"
npm verb node v12.16.1
npm verb npm  v6.13.4
npm ERR! code ELIFECYCLE
npm ERR! errno 3221225477
npm ERR! testwebgl@1.0.0 test: `jest --no-cache`
npm ERR! Exit status 3221225477
npm ERR!
npm ERR! Failed at the testwebgl@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 3221225477, true ]
npm timing npm Completed in 1852ms
```

Do you guys have any idea if this is a bug on your end or on `jest`'s? Or any least any hints of would I even go about debugging this further? I think it's related to `jest`'s environment, but I get zero feedback.. 

Thanks!

**Comment by dhritzkiv** [comment]
This may be due to how `gl` isn’t enabled for parallel/context-aware work, and how jest is specifically designed for being run in parallel.

I see you’ve tried the suggestion posted in the other jest issue.

For your jest options, could you try also passing [--runInBand](https://jestjs.io/docs/en/cli.html#--runinband)?

**Comment by 1danielcoelho** [comment]
That's right, that's where I got `--no-cache` from :)

All combinations of `--runInBand` and `--no-cache` produce the exact same segfault.

Can you reproduce this on your end?

**Comment by dhritzkiv** [comment]
I couldn't reproduce this on my end. I ran this in jest with and without any options and it passed the test just fine.

I ran this on macOS 10.15.4 on nodejs 12 and 14. I just noticed that you're running Windows. Perhaps it's a platform-specific issue?

Are you able to run this library OK separately from jest? Alternatively, could you run your test suite on another OS/environment (Docker, WSL, Linux in a VM locally or in the cloud, etc.)

Note: none of the active maintainers have ready access to a Windows machine to help debug this. You may have to pull down this repo and do some spelunking with Visual studio's equivalent of lldb to debug the native portion of this library.
