### ISSUE TITLE
Can't install on Mac Catalina

### ISSUE THREAD

**Issue by ricardoekm** [stackgl/headless-gl#193]
Environment:
* mac OS version: 10.15.5 
* node version: v13.10.1
* node-gyp version: v5.0.7

node-gyp raises the error below. Any help is appreciated, thanks!
```
npm install gl

> gl@4.5.2 install /Users/ricardomayerhofer/Projetos/OS/deck.gl/node_modules/gl
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=13.10.1 runtime=node arch=x64 libc= platform=darwin)
Traceback (most recent call last):
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
    return main(sys.argv[1:])
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
    return gyp_main(args)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 523, in gyp_main
    options.duplicate_basename_check)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 139, in Load
    params['parallel'], params['root_targets'])
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2868, in Load
    SetUpConfigurations(target, target_dict)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2289, in SetUpConfigurations
    for configuration in target_dict['configurations'].keys():
RuntimeError: dictionary changed size during iteration
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:316:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.5.0

```

**Comment by dhritzkiv** [comment]
Very curious. What version of Python is on your system?

We have prebuilds for current and future LTS versions of Node, and chose to skip v13. Still, it should build…

Is there any way you can use node.js v14 or v12?

**Comment by ricardoekm** [comment]
My python is 3.7.4

```
python --version
Python 3.7.4
```

But in Node 14 it works nicely. Thanks!

**Comment by dhritzkiv** [comment]
Glad it worked out for you.

Just in case you (or anyone else) are curious, I believe this is an issue with Python 3 and node-gyp 5.0.

Using Python 2, or Python 3 with a newer version of node-gyp should resolve local build issues.
