### ISSUE TITLE
Cannot install on windows.

### ISSUE THREAD

**Issue by TheTrueGravity** [stackgl/headless-gl#210]
I tried running `npm install brain.js` and that gave me an error. It seemed to be coming from gl. So, I tried `npm install gl` and that gave the same errors

Here is the install output:

```
C:\Users\charl\Desktop\mavis-utils>npm install gl
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> gl@4.9.0 install C:\Users\charl\Desktop\mavis-utils\node_modules\gl
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=14.15.1 runtime=node arch=ia32 libc= platform=win32)

C:\Users\charl\Desktop\mavis-utils\node_modules\gl>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\charl\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Warning: Missing input files:
C:\Users\charl\Desktop\mavis-utils\node_modules\gl\deps\windows\dll\ia32\libEGL.dll
C:\Users\charl\Desktop\mavis-utils\node_modules\gl\deps\windows\dll\ia32\d3dcompiler_47.dll
C:\Users\charl\Desktop\mavis-utils\node_modules\gl\deps\windows\dll\ia32\libGLESv2.dll
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Copying C:\Users\charl\Desktop\mavis-utils\node_modules\gl/deps/windows/dll/ia32/d3dcompiler_47.dll to C:\Users\charl\Desktop\mavis-utils\node_modules\gl\build\Release
  The system cannot find the path specified.
  Copying C:\Users\charl\Desktop\mavis-utils\node_modules\gl/deps/windows/dll/ia32/libEGL.dll to C:\Users\charl\Desktop\mavis-utils\node_modules\gl\build\Release
  The system cannot find the path specified.
  Copying C:\Users\charl\Desktop\mavis-utils\node_modules\gl/deps/windows/dll/ia32/libGLESv2.dll to C:\Users\charl\Desktop\mavis-utils\node_modules\gl\build\Release
  The system cannot find the path specified.
  bindings.cc
  webgl.cc
  procs.cc
  win_delay_load_hook.cc
LINK : fatal error LNK1104: cannot open file 'libEGL.lib' [C:\Users\charl\Desktop\mavis-utils\node_modules\gl\build\webgl.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\charl\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\charl\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\charl\Desktop\mavis-utils\node_modules\gl
gyp ERR! node -v v14.15.1
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gl@4.9.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gl@4.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\charl\AppData\Roaming\npm-cache\_logs\2020-12-14T19_59_46_429Z-debug.log
```

npm version:     6.14.8
node version:    14.15.1 x86
os:                      windows x64

**Comment by dhritzkiv** [comment]
Are you sure your Windows is x64? The output above suggests it's 32bit (`ia32`). Is node/npm somehow running in 32bit mode?

**Comment by dhritzkiv** [comment]
If it is, in fact, 32bit Windows, there are several issues that are related: #96, #176, #190.

It mostly boils down to us missing 32bit dlls for libEGL/libGLESv2. We're not sure where to procure them for 32bit Window, or how to link them if they're already present on a user's machine.

**Comment by TheTrueGravity** [comment]
I am certain it is x64 windows. Is it node js that is the issue, as it is an x86 install?

**Comment by TheTrueGravity** [comment]
I have fixed this by installing an x64 version of node js. Thankyou for the help!
