### ISSUE TITLE
gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp

### ISSUE THREAD

**Issue by smiilliin** [stackgl/headless-gl#250]
I'm trying to install headless gl on debian linux 11 and npm@9.6.3

I got the following gyp error:

```bash
smile@smile:~/yt-stream$ npm install headless-gl
```
```
npm ERR! code 2
npm ERR! path /home/smile/yt-stream/node_modules/headless-gl
npm ERR! command failed
npm ERR! command sh -c prebuild --install
npm ERR! prebuild info begin Prebuild version 5.1.2
npm ERR! prebuild http GET https://nodejs.org/download/release/v19.6.0/node-v19.6.0-headers.tar.gz
npm ERR! prebuild http 200 https://nodejs.org/download/release/v19.6.0/node-v19.6.0-headers.tar.gz
npm ERR! prebuild http GET https://nodejs.org/download/release/v19.6.0/SHASUMS256.txt
npm ERR! prebuild http 200 https://nodejs.org/download/release/v19.6.0/SHASUMS256.txt
npm ERR! prebuild info spawn /usr/bin/python2
npm ERR! prebuild info spawn args [
npm ERR! prebuild info spawn args   '/home/smile/yt-stream/node_modules/prebuild/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! prebuild info spawn args   'binding.gyp',
npm ERR! prebuild info spawn args   '-f',
npm ERR! prebuild info spawn args   'make',
npm ERR! prebuild info spawn args   '-I',
npm ERR! prebuild info spawn args   '/home/smile/yt-stream/node_modules/headless-gl/build/config.gypi',
npm ERR! prebuild info spawn args   '-I',
npm ERR! prebuild info spawn args   '/home/smile/yt-stream/node_modules/prebuild/node_modules/node-gyp/addon.gypi',
npm ERR! prebuild info spawn args   '-I',
npm ERR! prebuild info spawn args   '/home/smile/yt-stream/node_modules/headless-gl/19.6.0/include/node/common.gypi',
npm ERR! prebuild info spawn args   '-Dlibrary=shared_library',
npm ERR! prebuild info spawn args   '-Dvisibility=default',
npm ERR! prebuild info spawn args   '-Dnode_root_dir=/home/smile/yt-stream/node_modules/headless-gl/19.6.0',
npm ERR! prebuild info spawn args   '-Dnode_gyp_dir=/home/smile/yt-stream/node_modules/prebuild/node_modules/node-gyp',
npm ERR! prebuild info spawn args   '-Dnode_lib_file=/home/smile/yt-stream/node_modules/headless-gl/19.6.0/<(target_arch)/node.lib',
npm ERR! prebuild info spawn args   '-Dmodule_root_dir=/home/smile/yt-stream/node_modules/headless-gl',
npm ERR! prebuild info spawn args   '-Dnode_engine=v8',
npm ERR! prebuild info spawn args   '--depth=.',
npm ERR! prebuild info spawn args   '--no-parallel',
npm ERR! prebuild info spawn args   '--generator-output',
npm ERR! prebuild info spawn args   'build',
npm ERR! prebuild info spawn args   '-Goutput_dir=.'
npm ERR! prebuild info spawn args ]
npm ERR! gyp: Undefined variable standalone_static_library in binding.gyp while trying to load binding.gyp
npm ERR! prebuild ERR! configure error 
npm ERR! prebuild ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! prebuild ERR! stack     at ChildProcess.onCpExit (/home/smile/yt-stream/node_modules/prebuild/node_modules/node-gyp/lib/configure.js:345:16)
npm ERR! prebuild ERR! stack     at ChildProcess.emit (node:events:512:28)
npm ERR! prebuild ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm ERR! prebuild ERR! not ok 
npm ERR! prebuild ERR! build Error: `gyp` failed with exit code: 1
npm ERR! prebuild ERR! build     at ChildProcess.onCpExit (/home/smile/yt-stream/node_modules/prebuild/node_modules/node-gyp/lib/configure.js:345:16)
npm ERR! prebuild ERR! build     at ChildProcess.emit (node:events:512:28)
npm ERR! prebuild ERR! build     at ChildProcess._handle.onexit (node:internal/child_process:293:12)

npm ERR! A complete log of this run can be found in: /home/smile/.npm/_logs/2023-04-02T05_22_07_530Z-debug-0.log
```

**Comment by dhritzkiv** [comment]
headless-gl only supports LTS versions of node: 14, 16, 18.

Installing on other versions will cause the binary to be built from source, which currently doesn't work in v19, it seems.
