### ISSUE TITLE
Ubuntu `Error creating WebGLContext`

### ISSUE THREAD

**Issue by kevzettler** [stackgl/headless-gl#48]
The npm install had no errors and pretty sure I have all the system dependencies.  How can I confirm?
```
root@1e01255122e7:/srv/www# node
> var gl = require('gl')
undefined
> gl()
Error: Error creating WebGLContext
    at Error (native)
    at createContext (/dist/node_modules/gl/index.js:36:12)
    at repl:1:1
    at REPLServer.defaultEval (repl.js:252:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:417:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:210:10)
```

**Comment by arcanis** [comment]
@kevzettler Did you solved it ?

**Comment by kevzettler** [comment]
@arcanis  no I ended up using webgl with electron-spawn
