### ISSUE TITLE
question for win32

### ISSUE THREAD

**Issue by tzvetelin-vassilev** [stackgl/headless-gl#96]
Hi guys,

I just wondering about dependencies for windows x86 platform. Are there some troubles with x86 build. Could you include needed deps for x86 or to recommend what to use. Currently I have troubles to build for x86 platform.

Regards,
Tzvetelin Vassilev

**Comment by mourner** [comment]
Hi, can you please provide more information on what troubles you encountered exactly? Have you consulted the [Readme notes on Windows](https://github.com/stackgl/headless-gl#system-dependencies)?

**Comment by tzvetelin-vassilev** [comment]
Generally after npm install:

npm WARN prefer global node-gyp@3.5.0 should be installed with -g
npm WARN prefer global node-ninja@1.0.2 should be installed with -g

> gl@4.0.3 install C:\Projects\gl-app\node_modules\gl
> prebuild --install

prebuild info begin Prebuild version 5.1.2
prebuild info looking for local prebuild @ prebuilds\gl-v4.0.3-node-v51-win32-ia32.tar.gz
prebuild info looking for cached prebuild @ C:\Users\Samsung\AppData\Roaming\npm-cache\_prebuilds\https-github.com-stackgl-headless-gl-releases-download-v4.0.3-gl-v4.0.3-node-v51-win32-ia32.tar.gz
prebuild http request GET https://github.com/stackgl/headless-gl/releases/download/v4.0.3/gl-v4.0.3-node-v51-win32-ia32.tar.gz
prebuild http 404 https://github.com/stackgl/headless-gl/releases/download/v4.0.3/gl-v4.0.3-node-v51-win32-ia32.tar.gz
prebuild WARN install No prebuilt binaries found (target=7.2.1 runtime=node arch=ia32 platform=win32)
prebuild info install We will now try to compile from source.
Warning: Missing input files:
C:\Projects\gl-app\node_modules\gl\deps\windows\dll\ia32\libGLESv2.dll
C:\Projects\gl-app\node_modules\gl\deps\windows\dll\ia32\libEGL.dll
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Copying C:\Projects\gl-app\node_modules\gl/deps/windows/dll/ia32/libGLESv2.dll to C:\Projects\gl-app\node_modules\gl\build\Release\libGLESv2.dll
  The system cannot find the path specified.
  Copying C:\Projects\gl-app\node_modules\gl/deps/windows/dll/ia32/libEGL.dll to C:\Projects\gl-app\node_modules\gl\build\Release\libEGL.dll
  The system cannot find the path specified.
  bindings.cc
  webgl.cc
  procs.cc
  win_delay_load_hook.cc
..\src\webgl.cc(778): warning C4244: '*=' : conversion from 'double' to 'unsigned char', possible loss of data [C:\Projects\gl-app\node_modules\gl\build\webgl.vcxproj]
..\src\webgl.cc(780): warning C4244: 'initializing' : conversion from 'double' to 'float', possible loss of data [C:\Projects\gl-app\node_modules\gl\build\webgl.vcxproj]
..\src\webgl.cc(781): warning C4244: '*=' : conversion from 'float' to 'unsigned char', possible loss of data [C:\Projects\gl-app\node_modules\gl\build\webgl.vcxproj]
..\src\webgl.cc(782): warning C4244: '*=' : conversion from 'float' to 'unsigned char', possible loss of data [C:\Projects\gl-app\node_modules\gl\build\webgl.vcxproj]
..\src\webgl.cc(783): warning C4244: '*=' : conversion from 'float' to 'unsigned char', possible loss of data [C:\Projects\gl-app\node_modules\gl\build\webgl.vcxproj]
..\src\webgl.cc(790): warning C4244: 'initializing' : conversion from 'double' to 'float', possible loss of data [C:\Projects\gl-app\node_modules\gl\build\webgl.vcxproj]
..\src\webgl.cc(791): warning C4244: '*=' : conversion from 'float' to 'int', possible loss of data [C:\Projects\gl-app\node_modules\gl\build\webgl.vcxproj]
..\src\webgl.cc(792): warning C4244: '*=' : conversion from 'float' to 'int', possible loss of data [C:\Projects\gl-app\node_modules\gl\build\webgl.vcxproj]
..\src\webgl.cc(793): warning C4244: '*=' : conversion from 'float' to 'int', possible loss of data [C:\Projects\gl-app\node_modules\gl\build\webgl.vcxproj]
LINK : fatal error LNK1104: cannot open file 'libEGL.lib' [C:\Projects\gl-app\node_modules\gl\build\webgl.vcxproj]
prebuild ERR! build error 
prebuild ERR! stack Error: `C:\Program Files\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
prebuild ERR! stack     at ChildProcess.onExit (C:\Projects\gl-app\node_modules\node-gyp\lib\build.js:276:23)
prebuild ERR! stack     at emitTwo (events.js:106:13)
prebuild ERR! stack     at ChildProcess.emit (events.js:191:7)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
prebuild ERR! not ok 
prebuild ERR! build Error: `C:\Program Files\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
prebuild ERR! build     at ChildProcess.onExit (C:\Projects\gl-app\node_modules\node-gyp\lib\build.js:276:23)
prebuild ERR! build     at emitTwo (events.js:106:13)
prebuild ERR! build     at ChildProcess.emit (events.js:191:7)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gl-app@1.0.10 C:\Projects\gl-app
`-- d@0.1.1  extraneous

npm WARN gl-app@1.0.10 No repository field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "gl"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! gl@4.0.3 install: `prebuild --install`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the gl@4.0.3 install script 'prebuild --install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs gl
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls gl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Projects\gl-app\npm-debug.log

**Comment by OliaMi** [comment]
Dear  mourner,

Could you please follow up on the error posted above. It is important to understand where the problem is.

Thank you

**Comment by mourner** [comment]
Unfortunately I have no idea what's going on, and don't have a Windows machine to test. I just asked for details in case someone with relevant experience comes to triage the ticket.

**Comment by simonbuchan** [comment]
The issue is exactly as described by OP: you only have prebuilt `x64` binaries, he's compiling for `ia32`, the relevant part here:

```
prebuild WARN install No prebuilt binaries found (target=7.2.1 runtime=node arch=ia32 platform=win32)
prebuild info install We will now try to compile from source.
Warning: Missing input files:
C:\Projects\gl-app\node_modules\gl\deps\windows\dll\ia32\libGLESv2.dll
C:\Projects\gl-app\node_modules\gl\deps\windows\dll\ia32\libEGL.dll
```

Not exactly sure what your build steps are for pre-compiling ANGLE, but essentially https://stackoverflow.com/questions/22448885/how-do-i-build-32-bit-binaries-on-a-64-bit-system-using-npm says `node-gyp [...] --arch=ia32` or `node-pre-gyp [...] --target_arch=ia32`.

That said, not sure if it's worth doing much here: https://nodejs.org/en/ does not offer 32-bit node by default, so I would say at most provide instructions to build ANGLE yourself: unfortunately this looks like a bit of a pain to figure out yourself.
